services:

    dashboard:
        image: grafana/grafana-oss:9.4.7
        user: $CURRENT_UID
        ports:
            - '3000:3000'
        volumes:
            - './data:/var/lib/grafana/data'
            - './config/dashboards:/var/lib/grafana/dashboards'  
            - './config/provisioning:/var/lib/grafana/provisioning'  
            - './config/grafana.ini:/var/lib/grafana/grafana.ini'  
        environment:
            - GF_PATHS_CONFIG=/var/lib/grafana/grafana.ini
            - GF_PATHS_DATA=/var/lib/grafana/data
            - GF_PATHS_PROVISIONING=/var/lib/grafana/provisioning
            - INFLUXDB_TOKEN=${DB_ADMIN_INITIAL_TOKEN}
            - INFLUXDB_ORG=${DB_ORG}
            - INFLUXDB_BUCKET=${DB_BUCKET}
        networks:
            internal:
                aliases:
                    - dashboard-ui.docker.local
        logging:
                driver: syslog
                options:
                        tag: docker-dashboard-ui
        restart: unless-stopped
        depends_on:
            - "mqtt_broker"
